-- 原始渠道账单独立保存；不能把结算金额直接当作期初余额或再次确认收款。
CREATE TABLE yc_vend_account_bill (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 tenant_id VARCHAR(64) NOT NULL DEFAULT '000000',
 bill_date DATE NOT NULL,
 income_amount DECIMAL(18,2) NOT NULL,
 fee_amount DECIMAL(18,2) NOT NULL,
 source_account VARCHAR(128) NOT NULL,
 owner_name VARCHAR(128) NOT NULL,
 source_role VARCHAR(64) NOT NULL,
 channel VARCHAR(64) NOT NULL,
 merchant_no VARCHAR(128) NOT NULL,
 arrival_date DATE NULL,
 settlement_amount DECIMAL(18,2) NOT NULL,
 settlement_status VARCHAR(64) NOT NULL,
 settlement_info VARCHAR(500) NULL,
 account_id BIGINT NULL,
 source_file VARCHAR(255) NOT NULL,
 source_row INT NOT NULL,
 file_hash CHAR(64) NOT NULL,
 identity_hash CHAR(64) NOT NULL,
 content_hash CHAR(64) NOT NULL,
 create_user BIGINT NULL, create_dept BIGINT NULL,
 create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 update_user BIGINT NULL,
 update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 status TINYINT NOT NULL DEFAULT 1, is_deleted TINYINT NOT NULL DEFAULT 0,
 UNIQUE KEY uk_account_bill_identity (tenant_id, identity_hash),
 KEY idx_account_bill_date (bill_date),
 KEY idx_account_bill_account (account_id, bill_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='渠道原始账单：保留收益、手续费、到账及结算状态，不自动过账';
